{
  inputs,
  pkgs,
  ...
}: {
  nixpkgs.overlays = [inputs.niri-flake.overlays.niri];
  imports = [
    inputs.niri-flake.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms.homeModules.niri
    inputs.dms-plugin-registry.modules.default
    ./settings.nix
    ./binds.nix
    ./rules.nix
  ];

  programs.dank-material-shell = {
    enable = true;
    enableDynamicTheming = false;
    quickshell = with inputs; {
      package = quickshell.packages.${pkgs.stdenv.hostPlatform.system}.default;
    };
    plugins = {
      dankBatteryAlerts.enable = true;
      aiAssistant.enable = true;
      calculator.enable = true;
      dankBitwarden.enable = true;
      dankDesktopWeather.enable = true;
      dankGifSearch.enable = true;
      dankKDEConnect.enable = true;
      dankPomodoroTimer.enable = true;
      displayManager.enable = true;
      niriScreenshot.enable = true;
      nixMonitor.enable = true;
      wallpaperDiscovery.enable = true;
    };
    niri = {
      enableSpawn = true;
      enableKeybinds = false;
      includes = {
        enable = true; # Enable config includes hack. Enabled by default.

        override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
        filesToInclude = [
          # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
          "alttab" # Please note that niri will throw an error if any of these files are missing.
          "binds"
          "colors"
          "layout"
          "outputs"
          "wpblur"
        ];
      };
    };
  };

  home.packages = with pkgs; [
    seatd
    xwayland-satellite
    jaq
  ];
}
