#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done


# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &


# Logitec mouse
solaar -w hide &

#NetworkManager tray
nm-applet &

#Joplin notes
joplin-desktop &

# OpenRazer
polychromatic-tray-applet &

#Wallpaper --use-scaled-window for faster scaling
wpaperd --use-scaled-window

#Cooler Control 
coolercontrol &
